name: gpu2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_win64_mkl
  - brotlipy=0.7.0=py310h8d17308_1005
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h628cb3f_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - cryptography=39.0.2=py310h6e82f81_0
  - cuda=11.7.1=0
  - cuda-cccl=11.7.91=0
  - cuda-command-line-tools=11.7.1=0
  - cuda-compiler=11.7.1=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cuobjdump=11.7.91=0
  - cuda-cupti=11.7.101=0
  - cuda-cuxxfilt=11.7.91=0
  - cuda-demo-suite=12.1.55=0
  - cuda-documentation=12.1.55=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=11.7.99=0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=11.7.91=0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=11.7.91=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-nvvp=12.1.55=0
  - cuda-runtime=11.7.1=0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=11.7.1=0
  - cuda-tools=11.7.1=0
  - cuda-visual-tools=11.7.1=0
  - debugpy=1.6.6=py310h00ffb61_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - freetype=2.12.1=h546665d_1
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - intel-openmp=2023.0.0=h57928b3_25922
  - ipykernel=6.21.3=pyh025b116_0
  - ipython=8.11.0=pyh08f2357_0
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.0.3=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py310h5588dad_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - lcms2=2.15=ha5c8aab_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=16_win64_mkl
  - libcblas=3.9.0=16_win64_mkl
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libhwloc=2.9.0=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - liblapack=3.9.0=16_win64_mkl
  - liblapacke=3.9.0=16_win64_mkl
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.39=h19919ed_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.40.0=hcfcfb64_0
  - libtiff=4.5.0=hf8721a0_2
  - libuv=1.44.2=h8ffe710_0
  - libwebp-base=1.2.4=h8ffe710_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.3=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_4
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - mkl-devel=2022.1.0=h57928b3_875
  - mkl-include=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nsight-compute=2023.1.0.15=0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.1.0=hcfcfb64_0
  - packaging=23.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310hdbb7713_1
  - pip=23.0.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py310h8d17308_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h8d17308_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.10.9=h4de0772_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytorch=1.13.1=py3.10_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h67b0de4_1
  - pytorch-mutex=1.0=cuda
  - pywin32=304=py310h00ffb61_2
  - pyzmq=25.0.0=py310hcd737a0_0
  - requests=2.28.2=pyhd8ed1ab_0
  - setuptools=67.6.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=h91493d7_0
  - tk=8.6.12=h8ffe710_0
  - tornado=6.2=py310h8d17308_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - vc=14.3=hb6edc58_10
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zstd=1.5.2=h12be248_6
  - pip:
      - adagio==0.2.4
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - ansi2html==1.8.0
      - antlr4-python3-runtime==4.11.1
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - catboost==1.1.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - cmdstanpy==1.1.0
      - contourpy==1.0.7
      - convertdate==2.4.0
      - cycler==0.11.0
      - cython==0.29.33
      - darts==0.23.1
      - dash==2.8.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - docker-pycreds==0.4.0
      - ephem==4.1.4
      - flask==2.2.3
      - fonttools==4.39.0
      - frozenlist==1.3.3
      - fs==2.4.16
      - fsspec==2023.3.0
      - fugue==0.8.1
      - fugue-sql-antlr==0.1.5
      - gitdb==4.0.10
      - gitpython==3.1.31
      - greenlet==2.0.2
      - hijri-converter==2.2.4
      - holidays==0.21
      - ipython-genutils==0.2.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jupyter-dash==0.4.2
      - kiwisolver==1.4.4
      - korean-lunar-calendar==0.3.1
      - lightgbm==3.3.5
      - lightning-utilities==0.8.0
      - llvmlite==0.39.1
      - lunarcalendar==0.0.9
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - multidict==6.0.4
      - nbformat==4.2.0
      - nfoursid==1.0.1
      - numba==0.56.4
      - numpy==1.23.5
      - orjson==3.8.7
      - pandas==1.5.3
      - pathtools==0.1.2
      - patsy==0.5.3
      - plotly==5.13.1
      - plotly-resampler==0.8.3.2
      - pmdarima==2.0.2
      - prophet==1.1.2
      - protobuf==4.22.1
      - pyarrow==11.0.0
      - pymeeus==0.5.12
      - pyod==1.0.8
      - pyparsing==3.0.9
      - python-graphviz==0.20.1
      - pytorch-lightning==1.9.4
      - pytz==2022.7.1
      - pyyaml==6.0
      - qpd==0.4.0
      - retrying==1.3.4
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentry-sdk==1.16.0
      - setproctitle==1.3.2
      - shap==0.41.0
      - slicer==0.0.7
      - smmap==5.0.0
      - sqlalchemy==2.0.6
      - sqlglot==11.3.6
      - statsforecast==1.5.0
      - statsmodels==0.13.5
      - tbats==1.1.2
      - tenacity==8.2.2
      - threadpoolctl==3.1.0
      - torchaudio==0.13.1
      - torchmetrics==0.11.4
      - torchvision==0.14.1
      - tqdm==4.65.0
      - trace-updater==0.0.9
      - triad==0.8.3
      - tzdata==2022.7
      - wandb==0.13.11
      - werkzeug==2.2.3
      - xarray==2023.2.0
      - xgboost==1.7.4
      - yarl==1.8.2
prefix: C:\Users\nik\miniconda3\envs\gpu2
